### PR TITLE
rename and add tests

### PR DESCRIPTION
**Pull request by bshaffer**

### CODE REVIEW

**Comment by bshaffer** [comment]
@tmatsuo PTAL

**Comment by tmatsuo** [comment]
Can you provide what are changed? Can I see the changes in the generator rather than generated changes?

**Comment by bshaffer** [comment]
@tmatsuo https://github.com/bshaffer/apis-client-generator/commit/30fd801e0678cdbf3cfd848cc6634673431035ad

**Comment by bshaffer** [comment]
@tmatsuo removed all changes other than renaming/adding tests. PTAL

**Comment by tmatsuo** [comment]
LGTM

**Pull request merged**
