### PR TITLE
PHP docblock changed for better hints

### PR DESCRIPTION
**Pull request by shahariaazam**
It helps developer for faster understandings

### CODE REVIEW

**Comment by mattwhisenhunt** [comment]
Thanks for the contribution! These classes are autogenerated and any PR we merge will get overwritten.

**Comment by shahariaazam** [comment]
Ok. I understand and thanks for your reply. So shouldn't the classes be more descriptive? Because everytime to work with those classes, developer also need to study on original documentation page where it's very much possible that developer can get an idea about what to do and what they are doing.

**Comment by mattwhisenhunt** [comment]
Yeah, you're right. It is on the TODO list: google/google-api-php-client#408 but it hasn't gotten done yet. The way I get around it is always having a tab open to [API Explorer](https://developers.google.com/apis-explorer/#p/), but that is because I tend to not spend a lot of time with any one API.

Thanks again for taking the initiative and making some corner of open source a little better!

**Comment by shahariaazam** [comment]
Thanks @mattwhisenhunt for your response. Yea it will take some times to finish documenting everything. And it's not a good idea for doing by one person. Everybody can participate into that whoever want to. 
Because if the API is documented in correct way, that will save a developer lots of time.

**Pull request closed without merging**
